steps:
    - name: 'gcr.io/cloud-builders/docker'
      ###args: ['build', '-t', 'gcr.io/$PROJECT_ID/appinfo', '.']
      args: ['build',
         '-t',
         'gcr.io/$PROJECT_ID/appinfo:$SHORT_SHA',
         '.']
    - name: 'gcr.io/$PROJECT_ID/appinfo'
      #entrypoint : python AppInfo.py
      entrypoint: /bin/sh
      args ['-c', 'python AppUT.py']
      #args: ['run','gcr.io/$PROJECT_ID/appinfo']
images: ['gcr.io/pure-night-216804/appinfo:$SHORT_SHA']
