steps:
    - name: 'gcr.io/cloud-builders/docker'
      #args: ['build', '-t', 'gcr.io/$PROJECT_ID/appinfo', '.']
      args: ['build',
         '--build-arg',
         'node_version=${_NODE_VERSION_1}',
         '-t',
         'gcr.io/$PROJECT_ID/appinfo-${_NODE_VERSION_1}',
         '.']
substitutions:
        _NODE_VERSION_1: v.15
images: ['gcr.io/pure-night-216804/appinfo-${_NODE_VERSION_1}']