steps:
    - name: 'gcr.io/cloud-builders/docker'
      ###args: ['build', '-t', 'gcr.io/$PROJECT_ID/appinfo', '.']
      args: ['build',
         '-t',
         'gcr.io/$PROJECT_ID/appinfo:$SHORT_SHA',
         '.']
    - name: 'gcr.io/cloud-builders/docker'
      entrypoint : 'python AppInfo.py'
images: ['gcr.io/pure-night-216804/appinfo:$SHORT_SHA']
